language: python

python:
  - "2.7"
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls codecov
  - pip install pytest


script:
  - pytest --cov=app

after_success:
  - coveralls
